# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Linux

on:
  workflow_dispatch:
  workflow_call:
  workflow_run:
    workflows: ["build-3-os"]
    types:
      - requested

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: ['x86_64']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Generate TAG
        id: Tag
        run: |
          tag='continuous'
          name='Continuous Build'
          if [ 'true' == ${{ startsWith(github.ref, 'refs/tags/') }} ];then
            tag='${{ github.ref_name }}'
            name='${{ github.ref_name }}'
          fi
          echo "tag result: $tag - $name"
          echo "::set-output name=tag::$tag"
          echo "::set-output name=name::$name"
         
      - name: run-vcpkg
        uses: lukka/run-vcpkg@v11.5  # Option 2: specify 'latest' or 'latestrc' in the input version arguments:

      - name: Build
        run: |
          sudo apt install -y ninja-build
          tools/linux/ci.sh ${{ matrix.arch }} ${{ steps.tag.outputs.tag }}

      - name: Upload artifacts (if not triggered by build-3-os)
        if: ${{ github.event_name != 'build-3-os' }}
        uses: actions/upload-artifact@v4
        with:
          name: lin-artifact
          path: tmp/build
