# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Windows

on:
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest

    strategy:
      matrix:
        arch: ['x86_64']

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Generate TAG
        id: Tag
        run: |
          $tag="continuous"
          $name="Continuous Build"
          if ( "true" -eq "${{ startsWith(github.ref, 'refs/tags/') }}" ) {
            $tag="${{ github.ref_name }}"
            $name='${{ github.ref_name }}'
          }
          echo "tag result: $tag - $name"
          echo "::set-output name=tag::$tag"
          echo "::set-output name=name::$name"
         
      - name: run-vcpkg
        uses: lukka/run-vcpkg@v11.5  # Option 2: specify 'latest' or 'latestrc' in the input version arguments:

      - uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: ${{ matrix.arch }}
      - name: Build
        run: |
          powershell tools/windows/ci.ps1 ${{ matrix.arch }} ${{ steps.tag.outputs.tag }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          # Artifact name
          name: ${{ matrix.arch }}.build-win
          path: tmp/build
