# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Packages for All 3 OS

on:
  workflow_dispatch:
  workflow_call:
  workflow_run:
    workflows: ["release"]
    types:
      - requested

jobs:
  trigger-mac:
    uses: ./.github/workflows/build-mac-all.yml
    secrets: inherit

  trigger-win:
    uses: ./.github/workflows/build-win.yml
    secrets: inherit

  trigger-lin:
    uses: ./.github/workflows/build-lin.yml
    secrets: inherit

  upload-artifacts:
    runs-on: macos-latest
    needs:
      - trigger-mac
      - trigger-win
      - trigger-lin
    steps:
      - name: Download macOS Artifacts
        uses: actions/download-artifact@v4
        with:
          name: mac-all-artifact

      - name: Download Linux Artifacts
        uses: actions/download-artifact@v4
        with:
          name: lin-artifact

      - name: Download Windows Artifacts
        uses: actions/download-artifact@v4
        with:
          name: win-artifact

      - name: Upload artifacts (if not triggered by release)
        if: ${{ github.event_name != 'workflow_run' }}
        uses: actions/upload-artifact@v4
        with:
          name: build-3-os
          path: tmp/build
