# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build MacOS All (x86_64 & arm64)

on:
  workflow_dispatch:
  workflow_call:

jobs:
  trigger-arm64:
    uses: ./.github/workflows/build-mac-arm64.yml
    secrets: inherit

  trigger-x86_64:
    uses: ./.github/workflows/build-mac-x86_64.yml
    secrets: inherit
