# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build for All 3 OS

on:
  workflow_dispatch:
  workflow_call:

jobs:
  trigger-mac:
    uses: ./.github/workflows/build-mac-all.yml
    secrets: inherit

  trigger-win:
    uses: ./.github/workflows/build-win.yml
    secrets: inherit

  trigger-lin:
    uses: ./.github/workflows/build-lin.yml
    secrets: inherit
